# Generated by Django 5.0.1 on 2026-01-12 22:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique tenant identifier', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tenant organization name', max_length=255)),
                ('slug', models.SlugField(help_text='Unique tenant slug', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the tenant is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Tenant creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional tenant metadata')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='tenants_slug_3181c2_idx'), models.Index(fields=['is_active'], name='tenants_is_acti_ec1713_idx')],
            },
        ),
    ]
