# Generated by Django 5.0.1 on 2026-01-25 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique theme identifier', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Theme name', max_length=255)),
                ('version', models.CharField(default='1.0.0', help_text='Theme version (semantic versioning)', max_length=20)),
                ('is_preset', models.BooleanField(db_index=True, default=False, help_text='Whether this is an official preset theme')),
                ('theme_json', models.JSONField(help_text='Complete theme definition in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Theme creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this theme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_themes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this theme (null for presets)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'db_table': 'themes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_preset'], name='themes_is_pres_f99086_idx'), models.Index(fields=['tenant'], name='themes_tenant__eca172_idx'), models.Index(fields=['name'], name='themes_name_46e88a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_preset', True), ('tenant__isnull', True)), ('is_preset', False), _connector='OR'), name='preset_themes_no_tenant'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(fields=('name', 'tenant'), name='unique_theme_name_per_tenant'),
        ),
    ]
