# Generated by Django 5.0.1 on 2026-01-25 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_theme_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='theme',
            field=models.ForeignKey(blank=True, help_text='Selected theme for this tenant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_using', to='tenants.theme'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='theme_modes',
            field=models.JSONField(blank=True, default=list, help_text="Enabled theme modes (e.g., ['dark', 'compact'])"),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['theme'], name='tenants_theme_i_e0ad6f_idx'),
        ),
    ]
