# Generated by Django 5.0.1 on 2026-01-25 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_tenant_theme_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='base_preset',
            field=models.ForeignKey(blank=True, help_text='Base preset this theme extends (null for standalone themes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_themes', to='tenants.theme'),
        ),
        migrations.AddField(
            model_name='theme',
            name='token_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Token overrides to apply over base preset (empty for standalone themes)'),
        ),
    ]
