# Generated by Django 5.0.1 on 2026-01-26 05:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_theme_inheritance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantFeatureFlags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique feature flags identifier', primary_key=True, serialize=False)),
                ('flags', models.JSONField(blank=True, default=dict, help_text='Feature flags configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Feature flags creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('tenant', models.OneToOneField(help_text='Tenant these feature flags belong to', on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags_config', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Feature Flags',
                'verbose_name_plural': 'Tenant Feature Flags',
                'db_table': 'tenant_feature_flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantPageConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique page config identifier', primary_key=True, serialize=False)),
                ('pages', models.JSONField(blank=True, default=dict, help_text='Page configurations keyed by page path')),
                ('version', models.CharField(default='1.0.0', help_text='Page config schema version', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Page config creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('tenant', models.OneToOneField(help_text='Tenant this page config belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='page_config_data', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Page Configuration',
                'verbose_name_plural': 'Tenant Page Configurations',
                'db_table': 'tenant_page_configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique route identifier', primary_key=True, serialize=False)),
                ('path', models.CharField(help_text='Route path (e.g., /login, /dashboard)', max_length=255)),
                ('page_path', models.CharField(help_text='Page configuration path to render', max_length=255)),
                ('title', models.CharField(help_text='Page title', max_length=255)),
                ('exact', models.BooleanField(default=True, help_text='Whether the route path must match exactly')),
                ('protected', models.BooleanField(default=False, help_text='Whether the route requires authentication')),
                ('layout', models.CharField(default='main', help_text='Layout to use for this route', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order for navigation')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Route creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('tenant', models.ForeignKey(help_text='Tenant this route belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='routes_config', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Route',
                'verbose_name_plural': 'Tenant Routes',
                'db_table': 'tenant_routes',
                'ordering': ['tenant', 'order', 'path'],
                'indexes': [models.Index(fields=['tenant', 'path'], name='tenant_rout_tenant__e99150_idx'), models.Index(fields=['tenant', 'order'], name='tenant_rout_tenant__7e382b_idx')],
                'unique_together': {('tenant', 'path')},
            },
        ),
    ]
