# Generated by Django 5.0.1 on 2026-01-26 05:27

from django.db import migrations


def migrate_metadata_to_tables(apps, schema_editor):
    """
    Migrate existing metadata to new dedicated tables.
    """
    Tenant = apps.get_model('tenants', 'Tenant')
    TenantFeatureFlags = apps.get_model('tenants', 'TenantFeatureFlags')
    TenantPageConfig = apps.get_model('tenants', 'TenantPageConfig')
    TenantRoute = apps.get_model('tenants', 'TenantRoute')
    
    for tenant in Tenant.objects.all():
        metadata = tenant.metadata or {}
        
        # Migrate feature flags
        feature_flags = metadata.get('feature_flags', {})
        if feature_flags:
            TenantFeatureFlags.objects.create(
                tenant=tenant,
                flags=feature_flags
            )
        
        # Migrate page config
        page_config = metadata.get('page_config', {})
        if page_config:
            TenantPageConfig.objects.create(
                tenant=tenant,
                pages=page_config.get('pages', {}),
                version=page_config.get('version', '1.0.0')
            )
        
        # Migrate routes
        routes = metadata.get('routes', [])
        for route_data in routes:
            TenantRoute.objects.create(
                tenant=tenant,
                path=route_data.get('path', '/'),
                page_path=route_data.get('pagePath', '/'),
                title=route_data.get('title', 'Page'),
                exact=route_data.get('exact', True),
                protected=route_data.get('protected', False),
                layout=route_data.get('layout', 'main'),
                order=route_data.get('order', 0)
            )


def reverse_migration(apps, schema_editor):
    """
    Move data back to metadata if needed.
    """
    Tenant = apps.get_model('tenants', 'Tenant')
    TenantFeatureFlags = apps.get_model('tenants', 'TenantFeatureFlags')
    TenantPageConfig = apps.get_model('tenants', 'TenantPageConfig')
    TenantRoute = apps.get_model('tenants', 'TenantRoute')
    
    for tenant in Tenant.objects.all():
        metadata = tenant.metadata or {}
        
        # Migrate feature flags back
        try:
            feature_flags = TenantFeatureFlags.objects.get(tenant=tenant)
            metadata['feature_flags'] = feature_flags.flags
        except TenantFeatureFlags.DoesNotExist:
            pass
        
        # Migrate page config back
        try:
            page_config = TenantPageConfig.objects.get(tenant=tenant)
            metadata['page_config'] = {
                'pages': page_config.pages,
                'version': page_config.version
            }
        except TenantPageConfig.DoesNotExist:
            pass
        
        # Migrate routes back
        routes = []
        for route in TenantRoute.objects.filter(tenant=tenant).order_by('order'):
            routes.append({
                'path': route.path,
                'pagePath': route.page_path,
                'title': route.title,
                'exact': route.exact,
                'protected': route.protected,
                'layout': route.layout,
                'order': route.order
            })
        if routes:
            metadata['routes'] = routes
        
        tenant.metadata = metadata
        tenant.save(update_fields=['metadata'])


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_add_config_tables'),
    ]

    operations = [
        migrations.RunPython(migrate_metadata_to_tables, reverse_migration),
    ]
