# Generated by Django 5.0.1 on 2026-01-26 05:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


def migrate_old_flags_to_new(apps, schema_editor):
    """
    Migrate from old TenantFeatureFlags (OneToOne with JSON) to 
    new TenantFeatureFlag (ForeignKey with individual records).
    """
    Tenant = apps.get_model('tenants', 'Tenant')
    # Can't use the model directly since we're renaming, use raw SQL
    
    db_alias = schema_editor.connection.alias
    
    # Get old data before we drop the table
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT tenant_id, flags 
            FROM tenant_feature_flags_old
        """)
        old_flags_data = cursor.fetchall()
    
    # Create new records
    TenantFeatureFlag = apps.get_model('tenants', 'TenantFeatureFlag')
    for tenant_id, flags_json in old_flags_data:
        if not flags_json:
            continue
        
        tenant = Tenant.objects.get(id=tenant_id)
        
        for key, value in flags_json.items():
            # Handle both boolean values and dict values
            if isinstance(value, bool):
                enabled = value
                description = ''
            elif isinstance(value, dict):
                enabled = value.get('enabled', False)
                description = value.get('description', '')
            else:
                continue
            
            TenantFeatureFlag.objects.create(
                tenant=tenant,
                key=key,
                enabled=enabled,
                description=description
            )


def reverse_migration(apps, schema_editor):
    """
    Not implemented - too complex to reverse
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_migrate_metadata_to_tables'),
    ]

    operations = [
        # Step 1: Rename old table
        migrations.RunSQL(
            sql="ALTER TABLE tenant_feature_flags RENAME TO tenant_feature_flags_old;",
            reverse_sql="ALTER TABLE tenant_feature_flags_old RENAME TO tenant_feature_flags;"
        ),
        
        # Step 2: Create new TenantFeatureFlag model
        migrations.CreateModel(
            name='TenantFeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique feature flag identifier', primary_key=True, serialize=False)),
                ('key', models.CharField(help_text="Feature flag key (e.g., 'dark_mode', 'analytics')", max_length=100)),
                ('enabled', models.BooleanField(default=False, help_text='Whether this feature is enabled')),
                ('description', models.TextField(blank=True, help_text='Description of what this feature flag controls')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Feature flag creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('tenant', models.ForeignKey(help_text='Tenant this feature flag belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Feature Flag',
                'verbose_name_plural': 'Tenant Feature Flags',
                'db_table': 'tenant_feature_flags',
                'ordering': ['tenant', 'key'],
            },
        ),
        
        # Step 3: Add indexes
        migrations.AddIndex(
            model_name='tenantfeatureflag',
            index=models.Index(fields=['tenant', 'key'], name='tenant_feat_tenant__89bce0_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantfeatureflag',
            index=models.Index(fields=['tenant', 'enabled'], name='tenant_feat_tenant__40f87e_idx'),
        ),
        
        # Step 4: Add unique constraint
        migrations.AlterUniqueTogether(
            name='tenantfeatureflag',
            unique_together={('tenant', 'key')},
        ),
        
        # Step 5: Migrate data
        migrations.RunPython(migrate_old_flags_to_new, reverse_migration),
        
        # Step 6: Drop old table
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS tenant_feature_flags_old;",
            reverse_sql=""
        ),
    ]
