# Generated by Django 5.0.1 on 2026-01-26 05:49

from django.db import migrations


def migrate_feature_flags_to_records(apps, schema_editor):
    """
    Migrate feature flags from metadata JSON to individual TenantFeatureFlag records.
    """
    Tenant = apps.get_model('tenants', 'Tenant')
    TenantFeatureFlag = apps.get_model('tenants', 'TenantFeatureFlag')
    
    for tenant in Tenant.objects.all():
        metadata = tenant.metadata or {}
        feature_flags = metadata.get('feature_flags', {})
        
        # Create individual flag records from the JSON dict
        for key, value in feature_flags.items():
            # Handle both boolean values and dict values
            if isinstance(value, bool):
                enabled = value
                description = ''
            elif isinstance(value, dict):
                enabled = value.get('enabled', False)
                description = value.get('description', '')
            else:
                # Skip invalid values
                continue
            
            TenantFeatureFlag.objects.create(
                tenant=tenant,
                key=key,
                enabled=enabled,
                description=description
            )


def reverse_migration(apps, schema_editor):
    """
    Move feature flags back to metadata JSON.
    """
    Tenant = apps.get_model('tenants', 'Tenant')
    TenantFeatureFlag = apps.get_model('tenants', 'TenantFeatureFlag')
    
    for tenant in Tenant.objects.all():
        metadata = tenant.metadata or {}
        
        # Build feature flags dict from individual records
        feature_flags = {}
        for flag in TenantFeatureFlag.objects.filter(tenant=tenant):
            feature_flags[flag.key] = flag.enabled
        
        if feature_flags:
            metadata['feature_flags'] = feature_flags
            tenant.metadata = metadata
            tenant.save(update_fields=['metadata'])


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_refactor_feature_flags_table'),
    ]

    operations = [
        migrations.RunPython(migrate_feature_flags_to_records, reverse_migration),
    ]
