# Generated by Django 5.0.1 on 2026-01-28 02:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_migrate_feature_flags_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique template identifier', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name', max_length=255)),
                ('version', models.CharField(default='1.0.0', help_text='Template version (semantic versioning)', max_length=20)),
                ('is_preset', models.BooleanField(db_index=True, default=False, help_text='Whether this is an official preset template')),
                ('category', models.CharField(db_index=True, default='custom', help_text='Template category (landing, marketing, blog, etc.)', max_length=50)),
                ('tier', models.CharField(db_index=True, default='free', help_text='Template tier: free, premium, enterprise, custom', max_length=20)),
                ('template_json', models.JSONField(help_text='Complete template definition in JSON format')),
                ('template_overrides', models.JSONField(blank=True, default=dict, help_text='Template overrides to apply over base preset (empty for standalone templates)')),
                ('preview_image', models.CharField(blank=True, help_text='Preview/thumbnail image URL', max_length=500, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Template tags for search and filtering')),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Template creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('base_preset', models.ForeignKey(blank=True, help_text='Base preset this template extends (null for standalone templates)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_templates', to='tenants.template')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant that owns this template (null for presets)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Selected template for this tenant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_using_template', to='tenants.template'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['is_preset'], name='templates_is_pres_44bfff_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['tenant'], name='templates_tenant__ecd3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['name'], name='templates_name_061fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['category'], name='templates_categor_206a35_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['tier'], name='templates_tier_33e088_idx'),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_preset', True), ('tenant__isnull', True)), ('is_preset', False), _connector='OR'), name='preset_templates_no_tenant'),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(fields=('name', 'tenant'), name='unique_template_name_per_tenant'),
        ),
    ]
