# Generated by Django 5.0.1 on 2026-01-28 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_add_template_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantpageconfig',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='TenantFeatureFlags',
        ),
        migrations.DeleteModel(
            name='TenantPageConfig',
        ),
    ]
