# Generated by Django 5.0.1 on 2026-01-13 23:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique API client identifier', primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, help_text='Public client identifier (like username)', max_length=64, unique=True)),
                ('client_secret_hash', models.CharField(help_text='Hashed client secret (never stored in plaintext)', max_length=256)),
                ('name', models.CharField(help_text='Human-readable name for this API client', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Description of the client's purpose")),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this API client is active and can authenticate')),
                ('token_version', models.IntegerField(default=1, help_text='Token version - increment to invalidate all existing tokens')),
                ('roles', models.JSONField(blank=True, default=list, help_text="List of roles assigned to this client (e.g., ['read', 'write', 'admin'])")),
                ('scopes', models.JSONField(blank=True, default=list, help_text='List of scopes/permissions for this client')),
                ('rate_limit', models.IntegerField(blank=True, help_text='Custom rate limit for this client (requests per hour)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this API client was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this API client was last updated')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this API client last authenticated', null=True)),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='List of allowed IP addresses (empty = all IPs allowed)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for this client')),
                ('tenant', models.ForeignKey(help_text='Tenant this API client belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='api_clients', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'API Client',
                'verbose_name_plural': 'API Clients',
                'db_table': 'api_clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIClientUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, help_text='Client ID used in the attempt', max_length=64)),
                ('success', models.BooleanField(help_text='Whether the authentication attempt was successful')),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failure if authentication failed', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the authentication attempt occurred')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the attempt')),
                ('api_client', models.ForeignKey(blank=True, help_text='The API client that attempted authentication', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='authentication.apiclient')),
            ],
            options={
                'verbose_name': 'API Client Usage Log',
                'verbose_name_plural': 'API Client Usage Logs',
                'db_table': 'api_client_usage_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='apiclient',
            index=models.Index(fields=['client_id'], name='api_clients_client__52c9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='apiclient',
            index=models.Index(fields=['tenant', 'is_active'], name='api_clients_tenant__d34cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='apiclient',
            index=models.Index(fields=['is_active', 'last_used_at'], name='api_clients_is_acti_b7ea64_idx'),
        ),
        migrations.AddIndex(
            model_name='apiclientusagelog',
            index=models.Index(fields=['client_id', 'timestamp'], name='api_client__client__a01c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='apiclientusagelog',
            index=models.Index(fields=['api_client', 'timestamp'], name='api_client__api_cli_ab44f9_idx'),
        ),
        migrations.AddIndex(
            model_name='apiclientusagelog',
            index=models.Index(fields=['success', 'timestamp'], name='api_client__success_caa506_idx'),
        ),
    ]
